version: "3"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=example-api
    ports:
      - 3306:3306
  example-api:
    build:
      context: "."
      args:
        ENV: development
    environment:
      - PORT
      - SECRET=secret
      - NORM_ADAPTER=mysql
      - NORM_MYSQL_HOST=mysql
      - NORM_MYSQL_USER=root
      - NORM_MYSQL_PASSWORD=password
      - NORM_MYSQL_DATABASE=example-api
    volumes:
      - ".:/app"
    ports:
      - 3000:3000
    command: [ "npm", "run", "dev" ]
    depends_on:
      - mysql
